# Use the official Node.js image as the base image for backend
FROM node:latest AS backend

# Set the working directory for backend
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy backend source code
COPY quirknotes/backend ./

# Expose port 4000 to serve the backend
EXPOSE 4000

# Command to start the backend server
CMD ["npm", "run", "start"]

# Start a new stage for MongoDB
FROM mongo:latest

# Command to start MongoDB
CMD ["mongod", "--dbpath=/data/db"]
