services:
  frontend:
    image: qin2500/quirknotes_frontend:latest
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "3000:3000"
    environment:
    - ENV=Docker

  backend:
    image: qin2500/quirknotes_backend:latest
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
    - "4000:4000"
    environment:
    - ENV=Docker
    depends_on:
    - mongodb
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"