services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
      target: frontend
    ports:
      - "3000:3000"
    environment:
      - ENV=Docker
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"